### ISSUE TITLE
Your interpreter needs another test.

### ISSUE THREAD

**Issue by rdebath** [mirhagk/BF_Optimizer#1]
This "Hello World!" variant will currently fail.

``` brainfuck
>++++++++[<+++++++++>-]<.>>+>+>++>[-]+<[>[->+<<+
+++>]<<]>.+++++++..+++.>>+++++++.<<<[[-]<[-]>]<+
++++++++++++++.>>.+++.------.--------.>>+.>++++.
```

**Comment by mirhagk** [comment]
Ahh yes I forgot that `[` does the test, not `]`. I have fixed this problem. Just trying to determine if having 2 mechanisms for loops is worth the performance gain from a simple stack based previous one detection.

I haven't touched this project in quite some time, thanks for inspiring me to take another look at it.
